config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :recipes
    end
  end
  resources :users, only: [:show] do
    resources :cookbooks
  end

  resources :cookbooks, except: [:destory]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
  has_many :user_cookbooks
  has_many :users, through: :user_cookbooks

  belongs_to :creator, :class_name => "User", :foreign_key => :creator_id

  validates :title, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to  :recipe

  validates :name, presence: true
  validates :quantity, presence: true
  validates :unit_of_measurement, presence: true
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to  :recipe

  validates :body, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to  :user
  belongs_to  :cookbook
  has_many    :ingredients
  has_many    :instructions

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :user_cookbooks
 has_many :cookbooks, through: :user_cookbooks
 has_many :created_cookbooks, class_name: "Cookbook", foreign_key: :creator_id


  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user_cookbook.rb
class UserCookbook < ApplicationRecord
  belongs_to  :user
  belongs_to  :cookbook
end

app/controllers/api/v1/recipes_controller.rb
module Api
  module V1
    class RecipesController < ApiController
      def index
        render json: Recipe.all
      end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  def index
    @cookbooks= Cookbook.all
  end

  def new
    @user= current_user
    @cookbook = Cookbook.new
  end

  def create
    @user= current_user
    @cookbook = Cookbook.new(cookbook_params)
    if @cookbook.save
      join_cookbook(@user, @cookbook)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @cookbook= Cookbook.find(params[:id])
    @recipes= Recipe.where(cookbook_id: @cookbook)
  end

  def join_cookbook(user, cookbook)
    UserCookbook.create!(user_id: user.id, cookbook_id: cookbook.id)
  end

  def cookbook_params
    params.require(:cookbook).permit(:title, :creator_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user= current_user  
  end

end

app/controllers/recipes_controller.rb
def new
  @user= current_user
  @recipe = Recipe.new
end

def edit
  @recipe = Recipe.find(params[:id])
end

def create
  @user= current_user
  @recipe = Recipe.new(recipe_params)
  if @recipe.save
    redirect_to @recipe
  else
    render :new
  end
end


def show
  @recipe= Recipe.find(params[:id])
  @ingredients= Ingredient.where(recipe_id: @recipe)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= current_user
    @cookbooks_subscribed= @user.cookbooks
    @cookbooks_created= Cookbook.where(creator: @user)
  end

end

app/views/cookbooks/index.html.erb
<ul>
  <% @cookbooks.each do |cookbook| %>
    <li><%= link_to "#{cookbook.title}", cookbook_path(cookbook) %> - <%= cookbook.creator.full_name %></li>
  <% end %>
</ul>

app/views/cookbooks/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= form_for @cookbook do |f| %>
      <%= f.label :title %><%= f.text_field :title %>
      <%= f.hidden_field :creator_id, :value => @user.id %>
      <%= f.submit class:'button', id: 'new_form_sumbit'%>
    <% end %>
  </div>
</div>

app/views/cookbooks/show.html.erb
<%= @cookbook.title %>


<div id="app">
</div>

app/views/homes/index.html.erb
<div class="boxes-container">
  <% if @user %>
    <div class="row">
      <div class="small-12 medium-6 columns">
        <div class="boxes">
          <p class="boxes-text">
           <br/> <%= link_to 'Your Cookbooks', user_path(@user), class: "landing-page-links"%>
          </p>
        </div>
      </div>
      <div class="small-12 medium-6 columns">
        <div class="boxes">
          <p class="boxes-text">
           <br/> <%= link_to 'Browse All Cookbooks', cookbooks_path, class: "landing-page-links"%>
          </p>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="small-12 columns">
        <div class="boxes">
          <p class="boxes-text">
            Start building your household cookbook! <br/> <%= link_to 'Join Vittles Today', new_user_registration_path, class: "landing-page-links"%>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vittles</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Rammetto+One|Source+Sans+Pro' %>
  <%= stylesheet_link_tag 'application', 'https://use.fontawesome.com/releases/v5.0.6/css/all.css'%>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_pack_tag    'application' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="top-bar show-for-small-only" data-topbar role="navigation" data-options="is_hover: false">
    <section class="top-bar-section">
      <ul>
        <li class="has-dropdown title-text">
          <a id="title-text" href="/">Vittles</a>
          <ul id="mobile-nav-dropdown" class="dropdown">
            <li id="home-mobile-link"><a id="title-text" href="/">Home <i class="fas fa-utensils"></i></a></li>
            <% if current_user %>
              <li>
                <%= link_to 'New Cookbook', new_cookbook_path %>
              </li>
              <li>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Sign Up', new_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Sign In', new_user_session_path %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </section>
  </nav>


  <nav class="top-bar show-for-medium-up">
    <ul class="title-area">
      <li class="name">
        <h1 ><a id="title-text" href="/">V <i class="fas fa-utensils"></i></a></h1>
      </li>
    </ul>
    <% if current_user %>
      <section class="top-bar-section">
        <ul class="left">
          <li>
            <%= link_to 'New Cookbook', new_cookbook_path %>
          </li>
        </ul>
      </section>
    <% end %>


    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div id="flash-top-bar"class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <div class="yield">
  <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/recipes/show.html.erb
<%= @recipe.title %>

app/views/users/show.html.erb
<div class="user-nav-buttons-container">
</div>
<div class="user-show-container">
  <h1 class="user-first-name">
    <%= @user.first_name %>
  </h1>
  <h3 class="cookbooks-subheader">
    Cookbooks You Contribute To
  </h3>
  <div class="user-cookbooks-container">
    <ul>
      <% @cookbooks_subscribed.each do |cookbook| %>
        <li><%= link_to "#{cookbook.title}", cookbook_path(cookbook) %></li>
      <% end %>
    </ul>
  </div>
</div>